# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "Projects"
  url = "/projects/"
  weight = 20

[[main]]
  name = "Research"
  url = "/publication/"
  weight = 30

[[main]]
  name = "Talks"
  url = "/talk/"
  weight = 40

[[main]]
  name = "Experience"
  url = "/experience/"
  weight = 50

[[main]]
  name = "Open Source"
  url = "/open-source/"
  weight = 60

[[main]]
  name = "Resources"
  url = "/resources/"
  weight = 70

[[main]]
  name = "About"
  url = "/about/"
  weight = 80

[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/cv.pdf"
#    weight = 70
